#name, main, version and api are required
name: WorldCommander
main: tschrock\worldcommander\WorldCommander
version: 0.0.1
api: [1.4.0]

load: POSTWORLD
author: tschrock (tschrock123@gmail.com)
description: Command your worlds.
website: http://www.tschrock.net
commands:
 wc:
  description: Main WorldCommander command.
  usage: "/wc <flags|regions>"
 wcf:
  description: Manage flags.
  usage: "/wcf <help|list|info|set|unset>"
 wcr:
  description: Edit regions in a world.
  usage: "/wcr <pos1|pos2|create|delete|list>"
  aliases: ['regions', 'region']
permissions:
 tschrock.worldcommander.all:
  description: "Allows the user to use all WorldCommander commands."
  default: false
 tschrock.worldcommander.flags:
  description: "Allows the user to change all flags in a world."
  default: false
 tschrock.worldcommander.flags.exclude:
  description: "Allows the user to bypass all flags in a world."
  default: false
 tschrock.worldcommander.regions:
  description: "Allows the user to manage regions."
  default: false
 tschrock.worldcommander.regions.create:
  description: "Allows the user to create regions."
  default: false
 tschrock.worldcommander.regions.delete:
  description: "Allows the user to delete regions."
  default: false