## Main config for WorldCommander

# Whether or not Ops have all the permissions.
opHasAllPermissions: true

# Whether or not Ops bypass world flags.
opIsExcluded: false

# Whether or not someone with the 'tschrock.worldcommander.all' permission bypasses world flags.
worldcommander.allIsExcluded: false

# The amount of time, in ticks, between time updates.
# Smaller numbers will make the time look smoother, but will put more strain on the server.
timeUpdateInterval: 10